### ISSUE TITLE
Cookie cutter no longer working

### ISSUE THREAD

**Issue by emilhe** [plotly/dash-component-boilerplate#134]
I have previously been able to run this cookie cutter template on my Ubuntu, but when i tried today, it didn't work. I am getting the following error,

```
> dash_leaflet@0.0.1 build:js /home/emher/DashProjects4/dash_leaflet
> webpack --mode production

Hash: ade14534ef4733658c37
Version: webpack 4.36.1
Time: 1049ms
Built at: 11/07/2021 5:15:56 PM
 2 assets
Entrypoint main = dash_leaflet.min.js dash_leaflet.min.js.map dash_leaflet.min.js.map
[0] ./src/lib/index.js 3.79 KiB {0} [built] [failed] [1 error]

ERROR in ./src/lib/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/emher/DashProjects4/dash_leaflet/src/lib/index.js: Missing semicolon. (2:15)

  1 | /* eslint-disable import/prefer-default-export */
> 2 | import ' from './components/'.react';
    |                ^
  3 |
  4 | export {
  5 |     '
    at Object._raise (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:541:17)
    at Object.raiseWithData (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:534:17)
    at Object.raise (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:495:17)
    at Object.semicolon (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:3530:10)
    at Object.parseImport (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:14751:10)
    at Object.parseStatementContent (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:13387:27)
    at Object.parseStatement (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:13285:17)
    at Object.parseBlockOrModuleBlockBody (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:13874:25)
    at Object.parseBlockBody (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:13865:10)
    at Object.parseProgram (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:13207:10)
    at Object.parseTopLevel (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:13198:25)
    at Object.parse (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:14957:10)
    at parse (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/parser/lib/index.js:15009:38)
    at parser (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/core/lib/parser/index.js:52:34)
    at parser.next (<anonymous>)
    at normalizeFile (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/core/lib/transformation/normalize-file.js:87:38)
    at normalizeFile.next (<anonymous>)
    at run (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/core/lib/transformation/index.js:29:50)
    at run.next (<anonymous>)
    at Function.transform (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at step (/home/emher/DashProjects4/dash_leaflet/node_modules/gensync/index.js:261:32)
    at gen.next (/home/emher/DashProjects4/dash_leaflet/node_modules/gensync/index.js:273:13)
    at async.call.value (/home/emher/DashProjects4/dash_leaflet/node_modules/gensync/index.js:223:11)
    at errback.call (/home/emher/DashProjects4/dash_leaflet/node_modules/gensync/index.js:189:28)
    at runGenerator.errback (/home/emher/DashProjects4/dash_leaflet/node_modules/@babel/core/lib/gensync-utils/async.js:74:7)
    at val (/home/emher/DashProjects4/dash_leaflet/node_modules/gensync/index.js:113:33)
    at step (/home/emher/DashProjects4/dash_leaflet/node_modules/gensync/index.js:287:14)
    at gen.next (/home/emher/DashProjects4/dash_leaflet/node_modules/gensync/index.js:273:13)
    at async.call.value (/home/emher/DashProjects4/dash_leaflet/node_modules/gensync/index.js:223:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dash_leaflet@0.0.1 build:js: `webpack --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the dash_leaflet@0.0.1 build:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emher/.npm/_logs/2021-11-07T16_15_56_400Z-debug.log
post_gen_project command failed: npm run build:js
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 2)
```

Is this a known bug, or am I doing something wrong? :)

**Comment by alexcjohnson** [comment]
Looks like somehow `cookiecutter.component_name` got the value `'`?

https://github.com/plotly/dash-component-boilerplate/blob/75925fb6c10703b2e0b30d3f326799056349275c/%7B%7Bcookiecutter.project_shortname%7D%7D/src/lib/index.js#L2

(We can see that in line 5 as well)

Can you share what you used as inputs to the cookiecutter?

**Comment by emilhe** [comment]
I didn't note down the exact inputs, but now that I am trying again today, it just works. I'll re-open if the issue occurs again.
