### ISSUE TITLE
How to use _css_dist?

### ISSUE THREAD

**Issue by JoaoCarabetta** [plotly/dash-component-boilerplate#48]
I am trying to add a .css to my project following the instructions on the readme file.

 
> Make sure the stylesheets are added to the `_css_dist` dict in `deckglplotly/__init__.py` so dash will serve them automatically when the component suite is requested.

However, I do not know what is the key of the dict. When I try to put any key 

`_css_dist = [{'anykey': 'stlye.css'}]`

I get the following error:

```
Traceback (most recent call last):
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/dash/dash.py", line 997, in _setup_server
    self._generate_css_dist_html()
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/dash/dash.py", line 412, in _generate_css_dist_html
    self._collect_and_register_resources(self.css.get_all_css())
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/dash/resources.py", line 81, in get_all_css
    return self._resources.get_all_resources()
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/dash/resources.py", line 66, in get_all_resources
    return self._filter_resources(all_resources, dev_bundles)
  File "/Users/joaoc/Documents/Projects/deckglplotly/venv/lib/python3.6/site-packages/dash/resources.py", line 45, in _filter_resources
    s['external_url']
TypeError: 'set' object is not subscriptable
```

**Comment by JoaoCarabetta** [comment]
It worked! Thanks
