### ISSUE TITLE
Terser version causing build issues

### ISSUE THREAD

**Issue by mbkupfer** [plotly/dash-component-boilerplate#56]
`npm run build:all` was throwing the following error:

```
ERROR in dash_react_table.min.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/Users/mbk/dash_react_table/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
    at module.exports (/Users/mbk/dash_react_table/node_modules/terser-webpack-plugin/dist/worker.js:13:40)
    at handle (/Users/mbk/dash_react_table/node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (/Users/mbk/dash_react_table/node_modules/worker-farm/lib/child/index.js:51:3)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

This issue was brought up in vue as well and the advice there, which was to install `npm install terser@3.14` was able to fix this issue for me. Thought I would put this out on the radar.

**Comment by mbkupfer** [comment]
Here is that issue I reference from vue: https://github.com/vuejs/vue-cli/issues/3407
