### ISSUE TITLE
Type Error with Example

### ISSUE THREAD

**Issue by chschoenenberger** [plotly/dash-component-boilerplate#63]
Currently I am unable to run the vanilla boilerplate without any changes. I run cookiecutter with all default options except for the author name and email address. If I run "npm run start" on the newly generated project, it should display the example input component. However, I get the following error:

`TypeError: res.getHeader is not a function
    at processRequest (C:\source\my_dash_component\node_modules\webpack-dev-middleware\lib\middleware.js:82:18)
    at cbs.forEach (C:\source\my_dash_component\node_modules\webpack-dev-middleware\lib\context.js:52:9)
    at Array.forEach (<anonymous>)
    at process.nextTick (C:\source\my_dash_component\node_modules\webpack-dev-middleware\lib\context.js:51:11)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my_dash_component@0.0.1 start: `webpack-serve ./webpack.serve.config.js --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my_dash_component@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myUser\AppData\Roaming\npm-cache\_logs\2019-03-13T10_04_36_318Z-debug.log`

I assume there's something wrong with the dependencies. However, I am unable to resolve it myself.

**Comment by lavenderca** [comment]
Hi!  Did you make any progress resolving this error?  I'm running into the same issue.  Thanks!

**Comment by dolun** [comment]
Exactly the same problem:

TypeError: res.getHeader is not a function
    at processRequest (/Users/thomas/dash/composants_dash/node_modules/webpack-dev-middleware/lib/middleware.js:82:18)
    at cbs.forEach (/Users/thomas/dash/composants_dash/node_modules/webpack-dev-middleware/lib/context.js:52:9)
    at Array.forEach (<anonymous>)
    at process.nextTick (/Users/thomas/dash/composants_dash/node_modules/webpack-dev-middleware/lib/context.js:51:11)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! composants_dash@0.0.1 start: `webpack-serve ./webpack.serve.config.js --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the composants_dash@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomas/.npm/_logs/2019-03-22T21_03_22_508Z-debug.log

**Comment by mbkupfer** [comment]
Had the same issue on my end. 
`npm install webpack-dev-middleware@3.6.0` fixed this for me...hope it works for you!

As a side note,  adding a package-lock.json to the cookiecutter would be able to fix this.

**Comment by oipotty** [comment]
I have the same error and the `npm install webpack-dev-middleware@3.6.0` didn't work for me. Any other solutions? Thanks!
