### ISSUE TITLE
Error with cookiecutter 

### ISSUE THREAD

**Issue by oipotty** [plotly/dash-component-boilerplate#70]
Hello! I'm running into an issue when I try and run cookiecutter on the repo. I've went through the steps outlined in the ReadMe. I am running Python 3, and have successfully installed npm and node. However, my code returns an error when trying to run cookiecutter https://github.com/plotly/dash-component-boilerplate.git. 

I've seen #23  and I'm still not quite sure if I'm running into the same issue. 

Thanks in advance!

```

(venv) C:\p\venv\Scripts>npm -v
6.4.1

(venv) C:\p\venv\Scripts>node -v
v10.15.3

(venv) C:\p\venv\Scripts>cookiecutter https://github.com/plotly/dash-component-boilerplate.git
Traceback (most recent call last):
  File "C:\Users\GTX914\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\GTX914\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\p\venv\Scripts\cookiecutter.exe\__main__.py", line 9, in <module>
  File "c:\p\venv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\p\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\p\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\p\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\p\venv\lib\site-packages\cookiecutter\cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "c:\p\venv\lib\site-packages\cookiecutter\main.py", line 63, in cookiecutter
    password=password
  File "c:\p\venv\lib\site-packages\cookiecutter\repository.py", line 103, in determine_repo_dir
    no_input=no_input,
  File "c:\p\venv\lib\site-packages\cookiecutter\vcs.py", line 99, in clone
    stderr=subprocess.STDOUT,
  File "C:\Users\GTX914\anaconda3\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\GTX914\anaconda3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/plotly/dash-component-boilerplate.git']' returned non-zero exit status 128.


```

**Comment by chriddyp** [comment]
Thanks for reporting! Looking at
```
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/plotly/dash-component-boilerplate.git']' returned non-zero exit status 128.
```
it appears that the `git clone` step didn't work. Do you have git installed locally?

**Comment by oipotty** [comment]
Hey Chris, 
Thanks for the response. Git is installed locally as shown below and works as usual with another repo. 


```
(venv) C:\p\venv\Scripts>git clone https://github.com/plotly/dash-component-boilerplate.git
Cloning into 'dash-component-boilerplate'...
fatal: unable to access 'https://github.com/plotly/dash-component-boilerplate.git/': SSL certificate problem: self signed certificate in certificate chain

(venv) C:\p>git clone https://github.kdc.xxxxxxxxx.com/gtx914/MXReport.git
Cloning into 'MXReport'...
remote: Enumerating objects: 44, done.
remote: Total 44 (delta 0), reused 0 (delta 0), pack-reused 44
Unpacking objects: 100% (44/44), done.

(venv) C:\p>where git
C:\Users\GTX914\AppData\Local\Programs\Git\cmd\git.exe

```

**Comment by alexcjohnson** [comment]
odd, cloning this repo works fine for me (using either https or ssh), perhaps there's some sort of proxying in your network that's doing something repo-specific? Anyway, here's [one possible workaround](https://confluence.atlassian.com/fishkb/unable-to-clone-git-repository-due-to-self-signed-certificate-376838977.html)

```
git config --global http.sslVerify false
```

**Comment by oipotty** [comment]
Works great. Must have been the network proxy. Thanks a lot for the quick responses!
