### ISSUE TITLE
dash-generate-components doesn't allow whitespaces in path

### ISSUE THREAD

**Issue by Schaan** [plotly/dash-component-boilerplate#71]
Hi! Thank you for this neat boilerplate that brings me into the interplay of React and dash.
After all set up I tried to generate necessary python classes by running `npm run build:py`. There is an error with `Cannot find module <part of my project path>`. I guess the reason is that there is a whitespace in my working path and the `dash-generate-components`module (in Scripts) cannot recognize the complete path. Sorry I can't change it because it is set by our IT, but I think there could be a way to make this compatible.

**Comment by alexcjohnson** [comment]
Seems like a reasonable guess as to the root cause and we should be able to find a solution. Can you post the full error, with whatever traceback it includes? You can redact or mangle confidential info, but I'd like to see where exactly the code is failing and what part of your path the space is in.

**Comment by mram1000** [comment]
I got similar error - looks like due to whitespace in path to python interpreter.  How can I fix this pls? 

```
Executing: c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\python.exe -m venv venv
'c:\program' is not recognized as an internal or external command,
operable program or batch file.
post_gen_project command failed: c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\python.exe -m venv venv

        venv creation failed.
        Make sure you have installed virtualenv on python 2.

ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

```

**Comment by Schaan** [comment]
Hi @alexcjohnson sorry for the late reply! Finally got some free time for personal github 🤣 Here is the complete error:

**Comment by rashidamk** [comment]
hi, i am also facing this issue. please help 

(venv) (mydashenv) C:\OtherDocs\my_dash_component>npm run build

> my_dash_component@0.0.1 build C:\OtherDocs\my_dash_component
> npm run build:js && npm run build:py_and_r


> my_dash_component@0.0.1 build:js C:\OtherDocs\my_dash_component
> webpack --mode production

Hash: d9dbad6cc586fc09249e
Version: webpack 4.36.1
Time: 777ms
Built at: 08/04/2020 17:11:01
                       Asset      Size  Chunks             Chunk Names
    my_dash_component.min.js  3.18 KiB       0  [emitted]  main
my_dash_component.min.js.map  7.61 KiB       0  [emitted]  main
Entrypoint main = my_dash_component.min.js my_dash_component.min.js.map
[0] external "PropTypes" 42 bytes {0} [built]
[1] external "React" 42 bytes {0} [built]
[2] ./src/lib/index.js + 1 modules 5.15 KiB {0} [built]
    | ./src/lib/index.js 143 bytes [built]
    |     + 1 hidden module

> my_dash_component@0.0.1 build:py_and_r C:\OtherDocs\my_dash_component
> dash-generate-components ./src/lib/components my_dash_component

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'c:\users\rashida'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by rashidamk** [comment]
> hi, i am also facing this issue. please help
> 
> (venv) (mydashenv) C:\OtherDocs\my_dash_component>npm run build
> 
> > my_dash_component@0.0.1 build C:\OtherDocs\my_dash_component
> > npm run build:js && npm run build:py_and_r
> 
> > my_dash_component@0.0.1 build:js C:\OtherDocs\my_dash_component
> > webpack --mode production
> 
> Hash: d9dbad6cc586fc09249e
> Version: webpack 4.36.1
> Time: 777ms
> Built at: 08/04/2020 17:11:01
> Asset Size Chunks Chunk Names
> my_dash_component.min.js 3.18 KiB 0 [emitted] main
> my_dash_component.min.js.map 7.61 KiB 0 [emitted] main
> Entrypoint main = my_dash_component.min.js my_dash_component.min.js.map
> [0] external "PropTypes" 42 bytes {0} [built]
> [1] external "React" 42 bytes {0} [built]
> [2] ./src/lib/index.js + 1 modules 5.15 KiB {0} [built]
> | ./src/lib/index.js 143 bytes [built]
> | + 1 hidden module
> 
> > my_dash_component@0.0.1 build:py_and_r C:\OtherDocs\my_dash_component
> > dash-generate-components ./src/lib/components my_dash_component
> 
> internal/modules/cjs/loader.js:968
> throw err;
> ^
> 
> Error: Cannot find module 'c:\users\rashida'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
> at Function.Module._load (internal/modules/cjs/loader.js:841:27)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
> at internal/main/run_main_module.js:17:47 {
> code: 'MODULE_NOT_FOUND',
> requireStack: []

**Comment by rashidamk** [comment]
> hi, i am also facing this issue. please help
> 
> (venv) (mydashenv) C:\OtherDocs\my_dash_component>npm run build
> 
> > my_dash_component@0.0.1 build C:\OtherDocs\my_dash_component
> > npm run build:js && npm run build:py_and_r
> 
> > my_dash_component@0.0.1 build:js C:\OtherDocs\my_dash_component
> > webpack --mode production
> 
> Hash: d9dbad6cc586fc09249e
> Version: webpack 4.36.1
> Time: 777ms
> Built at: 08/04/2020 17:11:01
> Asset Size Chunks Chunk Names
> my_dash_component.min.js 3.18 KiB 0 [emitted] main
> my_dash_component.min.js.map 7.61 KiB 0 [emitted] main
> Entrypoint main = my_dash_component.min.js my_dash_component.min.js.map
> [0] external "PropTypes" 42 bytes {0} [built]
> [1] external "React" 42 bytes {0} [built]
> [2] ./src/lib/index.js + 1 modules 5.15 KiB {0} [built]
> | ./src/lib/index.js 143 bytes [built]
> | + 1 hidden module
> 
> > my_dash_component@0.0.1 build:py_and_r C:\OtherDocs\my_dash_component
> > dash-generate-components ./src/lib/components my_dash_component
> 
> internal/modules/cjs/loader.js:968
> throw err;
> ^
> 
> Error: Cannot find module 'c:\users\rashida'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
> at Function.Module._load (internal/modules/cjs/loader.js:841:27)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
> at internal/main/run_main_module.js:17:47 {
> code: 'MODULE_NOT_FOUND',
> requireStack: []

Just want to highlight that this issue has been fixed. I ended up using Git Bash instead of Command line to run the npm build and it worked fine!

**Comment by rashidamk** [comment]
Just want to highlight that the above issue has been fixed for me. I ended up using Git Bash instead of Command line to run the npm build and it worked fine!

**Comment by AtharvaKatre** [comment]
Hi, I was trying out this library for the first time and ran into this same issue.
Is there any update/fix on this? I don't want to switch to Git Bash as suggested by previous user, should I just avoid having white spaces in my path?

**Comment by ryanand26** [comment]
I'm new to python but in case it helps I think the issue is with the use of **shlex.split** in **post_gen_project.py**.

1. When you run the cookiecutter command for the first time it will download the dash-component-boilerplate script.
2. Go to that location. Mine was C:\\Users\username\.cookiecutters\dash-component-boilerplate
3. Open /hooks/post_gen_project.py
4. change subprocess.call to use 'cmd' not 'line'
5. Run the cookiecutter command and enter 'no' when asked if it should re-download the template
6. Let us know here if that works...

This got me past that particular error message.

**Comment by pythoro** [comment]
I had the same issue. I moved the package to a path without spaces to work around it.
